"use strict";

var React = require("react-native");

var { StyleSheet } = React;

module.exports = [
  {
    id: "0",
    name: "Kasandra Sides",
    image: require("../../assets/dummy/robert.png"),
    rating: 3.0,
    age: "23",
    categories: ["Fitness trainer", "Tai Chi", "Swimming", "HIIT"],
    coordinates: ["-77.02387957035339", "38.17001240327832"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita",
  },
  {
    id: "1",
    name: "Josh Damiani",
    image: require("../../assets/dummy/emilia.png"),
    rating: 4.5,
    age: "20",
    categories: ["Fitness trainer", "Personal defense"],
    coordinates: ["-77.08832451930029", "39.15567328478672"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus",
  },
  {
    id: "2",
    name: "Toney Stanger",
    image: require("../../assets/dummy/amanda.png"),
    rating: 5.0,
    age: "31",
    categories: ["Yoga", "HIIT"],
    coordinates: ["-77.00521098725912", "39.09652978208337"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no",
  },
  {
    id: "3",
    name: "Milissa Swihart",
    image: require("../../assets/dummy/amanda.png"),
    rating: 4.0,
    age: "38",
    categories: ["Martial art", "Tai Chi", "Zumba"],
    coordinates: ["-77.04467421298853", "39.24996441482515"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est",
  },
  {
    id: "4",
    name: "Beryl Kintzel",
    image: require("../../assets/dummy/junior.png"),
    rating: 5.0,
    age: "29",
    categories: ["Martial art", "Aerobics"],
    coordinates: ["-77.0578828971953", "38.87159570937383"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit",
  },
  {
    id: "5",
    name: "Sol Lumsden",
    image: require("../../assets/dummy/robert.png"),
    rating: 4.5,
    age: "21",
    categories: ["Swimming", "Pilates", "Aerobics"],
    coordinates: ["-76.90511581439429", "39.177249013509936"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd",
  },
  {
    id: "6",
    name: "Clelia Barranco",
    image: require("../../assets/dummy/kaitlyn.png"),
    rating: 3.5,
    age: "36",
    categories: ["Boxing", "Swimming", "HIIT"],
    coordinates: ["-76.93710318703278", "39.105324590960386"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita",
  },
  {
    id: "7",
    name: "Clark Cloe",
    image: require("../../assets/dummy/unknown.png"),
    rating: 5.0,
    age: "33",
    categories: ["Martial art", "Aerobics", "Personal defense"],
    coordinates: ["-77.00595178955508", "39.57483317621728"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam",
  },
  {
    id: "8",
    name: "Elfrieda Diniz",
    image: require("../../assets/dummy/kaitlyn.png"),
    rating: 3.0,
    age: "35",
    categories: ["Martial art", "Personal defense"],
    coordinates: ["-77.06501527172584", "39.020541005793184"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
  },
  {
    id: "9",
    name: "Kaila Gaeta",
    image: require("../../assets/dummy/amanda.png"),
    rating: 3.5,
    age: "37",
    categories: ["Strength trainer", "HIIT"],
    coordinates: ["-77.14018166482504", "38.91005356368109"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
  },
  {
    id: "10",
    name: "Eusebio Lyke",
    image: require("../../assets/dummy/robert.png"),
    rating: 3.5,
    age: "29",
    categories: ["Boxing", "Aerobics"],
    coordinates: ["-77.03576891988341", "39.087398765258285"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est",
  },
  {
    id: "11",
    name: "Rick Schissler",
    image: require("../../assets/dummy/amanda.png"),
    rating: 3.5,
    age: "25",
    categories: ["Fitness trainer", "HIIT"],
    coordinates: ["-77.08897200303221", "39.69338302308844"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam",
  },
  {
    id: "12",
    name: "Gertie Levis",
    image: require("../../assets/dummy/unknown.png"),
    rating: 4.0,
    age: "26",
    categories: ["Strength trainer", "Aerobics"],
    coordinates: ["-77.14621229784635", "38.43861052584394"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus",
  },
  {
    id: "13",
    name: "Darryl Piccirillo",
    image: require("../../assets/dummy/kaitlyn.png"),
    rating: 3.5,
    age: "23",
    categories: ["Marathon trainer", "HIIT", "Personal defense"],
    coordinates: ["-77.00313578992419", "38.31516235421885"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum",
  },
  {
    id: "14",
    name: "Mckinley Moisan",
    image: require("../../assets/dummy/kaitlyn.png"),
    rating: 4.0,
    age: "28",
    categories: ["Martial art", "HIIT"],
    coordinates: ["-77.02768890805879", "39.23495855581559"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,",
  },
  {
    id: "15",
    name: "Ross Bradstreet",
    image: require("../../assets/dummy/jefferson.png"),
    rating: 5.0,
    age: "26",
    categories: ["Fitness trainer", "Zumba", "Aerobics"],
    coordinates: ["-77.1213345168698", "38.9536666284862"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo",
  },
  {
    id: "16",
    name: "Roman Massenburg",
    image: require("../../assets/dummy/amanda.png"),
    rating: 4.5,
    age: "21",
    categories: ["Marathon trainer", "Aerobics"],
    coordinates: ["-77.16100831259652", "39.29194857588317"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam",
  },
  {
    id: "17",
    name: "Valerie Beaver",
    image: require("../../assets/dummy/jefferson.png"),
    rating: 3.0,
    age: "20",
    categories: ["Strength trainer", "Tai Chi", "Aerobics"],
    coordinates: ["-76.97004185342651", "38.67466896155779"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd",
  },
  {
    id: "18",
    name: "Stephanie Northrop",
    image: require("../../assets/dummy/amanda.png"),
    rating: 3.0,
    age: "37",
    categories: ["Strength trainer", "Tai Chi", "Pilates"],
    coordinates: ["-76.98196920765324", "39.26298226880467"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
  },
  {
    id: "19",
    name: "Vicente Acker",
    image: require("../../assets/dummy/pedro.png"),
    rating: 3.5,
    age: "38",
    categories: ["Marathon trainer", "Yoga"],
    coordinates: ["-77.15438546212086", "38.46075358991129"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus",
  },
  {
    id: "20",
    name: "Dionne Estep",
    image: require("../../assets/dummy/pedro.png"),
    rating: 4.5,
    age: "37",
    categories: ["Zumba", "Pilates"],
    coordinates: ["-77.20123040479187", "38.93541138274376"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam",
  },
  {
    id: "21",
    name: "Fernande Turnbull",
    image: require("../../assets/dummy/pedro.png"),
    rating: 4.0,
    age: "20",
    categories: ["Martial art", "Aerobics", "HIIT"],
    coordinates: ["-77.04043266022886", "38.95162648862346"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor",
  },
  {
    id: "22",
    name: "Yasuko Luque",
    image: require("../../assets/dummy/kaitlyn.png"),
    rating: 3.5,
    age: "25",
    categories: ["HIIT"],
    coordinates: ["-77.14366278904545", "39.366500653131"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At",
  },
  {
    id: "23",
    name: "Fae Marsico",
    image: require("../../assets/dummy/emilia.png"),
    rating: 3.0,
    age: "36",
    categories: ["Strength trainer"],
    coordinates: ["-76.96913528574987", "38.69572099079363"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem",
  },
  {
    id: "24",
    name: "Gerda Isherwood",
    image: require("../../assets/dummy/robert.png"),
    rating: 3.0,
    age: "30",
    categories: ["Yoga", "Aerobics"],
    coordinates: ["-77.19347434743511", "38.799177960197134"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero",
  },
  {
    id: "25",
    name: "Garry Whiting",
    image: require("../../assets/dummy/kaitlyn.png"),
    rating: 3.0,
    age: "30",
    categories: ["Boxing", "Yoga", "HIIT"],
    coordinates: ["-77.15437286566983", "39.424849386783315"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no",
  },
  {
    id: "26",
    name: "Adina Carder",
    image: require("../../assets/dummy/jefferson.png"),
    rating: 3.0,
    age: "28",
    categories: ["Yoga"],
    coordinates: ["-77.01573707242827", "39.14586858510561"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et",
  },
  {
    id: "27",
    name: "Brinda Clevinger",
    image: require("../../assets/dummy/jefferson.png"),
    rating: 3.0,
    age: "27",
    categories: ["Swimming"],
    coordinates: ["-77.0712304957296", "39.524172663405736"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit",
  },
  {
    id: "28",
    name: "Dionne Estep",
    image: require("../../assets/dummy/pedro.png"),
    rating: 5.0,
    age: "22",
    categories: ["Tai Chi", "Zumba"],
    coordinates: ["-77.11683221615255", "38.17699177281803"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At",
  },
  {
    id: "29",
    name: "Mahalia Ducker",
    image: require("../../assets/dummy/pedro.png"),
    rating: 4.0,
    age: "20",
    categories: ["Boxing", "Martial art", "Personal defense"],
    coordinates: ["-77.01646045236203", "38.725392377869696"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
  },
  {
    id: "30",
    name: "Noelle Rosel",
    image: require("../../assets/dummy/robert.png"),
    rating: 3.0,
    age: "23",
    categories: ["Pilates", "HIIT"],
    coordinates: ["-76.91791055174421", "39.235672592030056"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et",
  },
  {
    id: "31",
    name: "Ross Bradstreet",
    image: require("../../assets/dummy/emilia.png"),
    rating: 4.5,
    age: "33",
    categories: ["Martial art", "Pilates"],
    coordinates: ["-77.10348362169456", "39.267255953589654"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata",
  },
  {
    id: "32",
    name: "Leonila Childs",
    image: require("../../assets/dummy/jefferson.png"),
    rating: 5.0,
    age: "24",
    categories: ["Fitness trainer", "Yoga"],
    coordinates: ["-77.18131183280464", "38.40350646841374"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
  },
  {
    id: "33",
    name: "Claire Allbright",
    image: require("../../assets/dummy/robert.png"),
    rating: 3.0,
    age: "27",
    categories: ["Yoga", "Aerobics"],
    coordinates: ["-77.08376532733", "38.20615288513845"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores",
  },
  {
    id: "34",
    name: "Ira Melnick",
    image: require("../../assets/dummy/amanda.png"),
    rating: 4.5,
    age: "35",
    categories: ["Martial art", "Aerobics", "Personal defense"],
    coordinates: ["-76.97076514263054", "39.08819220521449"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero",
  },
  {
    id: "35",
    name: "Lina Granado",
    image: require("../../assets/dummy/jefferson.png"),
    rating: 4.0,
    age: "28",
    categories: ["Fitness trainer", "Tai Chi", "Zumba", "HIIT"],
    coordinates: ["-77.01431437920608", "38.2749270621102"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
  },
  {
    id: "36",
    name: "Hanh Halbrook",
    image: require("../../assets/dummy/robert.png"),
    rating: 3.5,
    age: "22",
    categories: ["Tai Chi"],
    coordinates: ["-77.01154137965432", "38.265818001661756"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
  },
  {
    id: "37",
    name: "Melvina Lindblom",
    image: require("../../assets/dummy/junior.png"),
    rating: 3.0,
    age: "25",
    categories: ["Boxing", "Strength trainer", "Tai Chi", "HIIT"],
    coordinates: ["-77.10302792655573", "38.7058814290286"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
  },
  {
    id: "38",
    name: "Donny Arledge",
    image: require("../../assets/dummy/jefferson.png"),
    rating: 3.0,
    age: "24",
    categories: ["Strength trainer", "Pilates"],
    coordinates: ["-77.07771687486017", "39.63352136612843"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est",
  },
  {
    id: "39",
    name: "Dane Ives",
    image: require("../../assets/dummy/pedro.png"),
    rating: 3.5,
    age: "23",
    categories: ["Marathon trainer", "Tai Chi"],
    coordinates: ["-76.9157001919923", "38.58715276762485"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam",
  },
  {
    id: "40",
    name: "Gertie Levis",
    image: require("../../assets/dummy/junior.png"),
    rating: 3.5,
    age: "38",
    categories: ["HIIT"],
    coordinates: ["-77.15729534838238", "39.438139173424204"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed",
  },
  {
    id: "41",
    name: "Ira Melnick",
    image: require("../../assets/dummy/emilia.png"),
    rating: 3.0,
    age: "35",
    categories: ["Zumba"],
    coordinates: ["-76.99392119863074", "38.53061544587022"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
  },
  {
    id: "42",
    name: "Sol Lumsden",
    image: require("../../assets/dummy/robert.png"),
    rating: 4.5,
    age: "35",
    categories: ["Tai Chi", "Personal defense"],
    coordinates: ["-77.20933633081947", "39.38043814434985"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem",
  },
  {
    id: "43",
    name: "Maryjane Spiller",
    image: require("../../assets/dummy/emilia.png"),
    rating: 5.0,
    age: "36",
    categories: ["Fitness trainer", "Tai Chi"],
    coordinates: ["-76.99262080728877", "39.61753970095241"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita",
  },
  {
    id: "44",
    name: "Felice Mclarty",
    image: require("../../assets/dummy/emilia.png"),
    rating: 3.0,
    age: "39",
    categories: ["Tai Chi", "Swimming", "Personal defense"],
    coordinates: ["-77.07067556522676", "38.943185858665075"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero",
  },
  {
    id: "45",
    name: "Venetta Mcelveen",
    image: require("../../assets/dummy/jefferson.png"),
    rating: 4.5,
    age: "27",
    categories: ["Zumba"],
    coordinates: ["-77.17319509517351", "39.1214578378392"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem",
  },
  {
    id: "46",
    name: "Boyce Neiman",
    image: require("../../assets/dummy/pedro.png"),
    rating: 3.0,
    age: "21",
    categories: ["Marathon trainer", "Tai Chi"],
    coordinates: ["-77.01957977813544", "38.976205802394055"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam",
  },
  {
    id: "47",
    name: "Karan Buteau",
    image: require("../../assets/dummy/emilia.png"),
    rating: 4.0,
    age: "29",
    categories: ["Swimming"],
    coordinates: ["-77.0426380095851", "38.856404116572705"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo",
  },
  {
    id: "48",
    name: "Jean Engstrom",
    image: require("../../assets/dummy/emilia.png"),
    rating: 4.5,
    age: "26",
    categories: ["Fitness trainer"],
    coordinates: ["-76.9304610761426", "38.60518440473185"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd",
  },
  {
    id: "49",
    name: "Venetta Mcelveen",
    image: require("../../assets/dummy/unknown.png"),
    rating: 3.5,
    age: "30",
    categories: ["Tai Chi"],
    coordinates: ["-77.1805984238513", "39.45330549221943"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum",
  },
  {
    id: "50",
    name: "Milissa Swihart",
    image: require("../../assets/dummy/pedro.png"),
    rating: 3.0,
    age: "29",
    categories: ["Boxing", "Martial art"],
    coordinates: ["-77.03865655677929", "39.03280956614662"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo",
  },
  {
    id: "51",
    name: "Charla Bradsher",
    image: require("../../assets/dummy/jefferson.png"),
    rating: 4.5,
    age: "37",
    categories: ["HIIT"],
    coordinates: ["-77.10707897444864", "38.212270133800175"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,",
  },
  {
    id: "52",
    name: "Karan Buteau",
    image: require("../../assets/dummy/emilia.png"),
    rating: 4.5,
    age: "32",
    categories: ["Swimming", "Pilates"],
    coordinates: ["-77.09375427353338", "38.94232746057918"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd",
  },
  {
    id: "53",
    name: "Hertha Nachman",
    image: require("../../assets/dummy/emilia.png"),
    rating: 4.0,
    age: "23",
    categories: ["Yoga", "Personal defense"],
    coordinates: ["-77.03860509380728", "39.124110528379525"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et",
  },
  {
    id: "54",
    name: "Michel Curnutte",
    image: require("../../assets/dummy/emilia.png"),
    rating: 5.0,
    age: "20",
    categories: ["Personal defense"],
    coordinates: ["-77.02013793516778", "39.41001244959452"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet",
  },
  {
    id: "55",
    name: "Mckinley Moisan",
    image: require("../../assets/dummy/jefferson.png"),
    rating: 3.0,
    age: "21",
    categories: ["Boxing"],
    coordinates: ["-77.14599386414564", "38.26979649880207"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed",
  },
  {
    id: "56",
    name: "Brinda Clevinger",
    image: require("../../assets/dummy/jefferson.png"),
    rating: 5.0,
    age: "29",
    categories: ["Pilates"],
    coordinates: ["-77.0153968295271", "39.11754449032621"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita",
  },
  {
    id: "57",
    name: "Vicente Acker",
    image: require("../../assets/dummy/kaitlyn.png"),
    rating: 3.0,
    age: "26",
    categories: ["Swimming", "Pilates"],
    coordinates: ["-77.09663923469117", "38.35194976902277"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit",
  },
  {
    id: "58",
    name: "Fae Marsico",
    image: require("../../assets/dummy/jefferson.png"),
    rating: 4.0,
    age: "20",
    categories: ["Yoga"],
    coordinates: ["-76.93911598178197", "39.32355376780039"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
  },
  {
    id: "59",
    name: "Vernia Mumme",
    image: require("../../assets/dummy/emilia.png"),
    rating: 4.5,
    age: "23",
    categories: ["Yoga", "Personal defense"],
    coordinates: ["-77.03827069122916", "38.87458698783659"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo",
  },
  {
    id: "60",
    name: "Kari Kesler",
    image: require("../../assets/dummy/kaitlyn.png"),
    rating: 4.0,
    age: "20",
    categories: ["Martial art", "HIIT"],
    coordinates: ["-76.97763327002374", "39.519121709727465"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo",
  },
  {
    id: "61",
    name: "Myesha Showman",
    image: require("../../assets/dummy/kaitlyn.png"),
    rating: 4.5,
    age: "34",
    categories: ["Aerobics"],
    coordinates: ["-76.91874398061502", "38.53350140911123"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam",
  },
  {
    id: "62",
    name: "Joye Koop",
    image: require("../../assets/dummy/pedro.png"),
    rating: 3.5,
    age: "29",
    categories: ["Martial art"],
    coordinates: ["-77.11533805686045", "38.43724855647767"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum",
  },
  {
    id: "63",
    name: "Kalyn Dallman",
    image: require("../../assets/dummy/pedro.png"),
    rating: 3.5,
    age: "36",
    categories: ["Martial art"],
    coordinates: ["-77.23938099136407", "38.92869604779271"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et",
  },
  {
    id: "64",
    name: "Erinn Sawyers",
    image: require("../../assets/dummy/junior.png"),
    rating: 3.5,
    age: "33",
    categories: ["Tai Chi", "Yoga"],
    coordinates: ["-76.96026225347701", "39.34513672023511"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor",
  },
  {
    id: "65",
    name: "Elfrieda Diniz",
    image: require("../../assets/dummy/pedro.png"),
    rating: 3.0,
    age: "22",
    categories: ["Fitness trainer", "Marathon trainer", "HIIT"],
    coordinates: ["-77.05146871631179", "38.991633711437025"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit",
  },
  {
    id: "66",
    name: "Roman Massenburg",
    image: require("../../assets/dummy/unknown.png"),
    rating: 4.0,
    age: "36",
    categories: ["Tai Chi", "Zumba"],
    coordinates: ["-77.01498510968412", "38.96390859050688"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
  },
  {
    id: "67",
    name: "Hae Durgin",
    image: require("../../assets/dummy/emilia.png"),
    rating: 3.0,
    age: "21",
    categories: ["Strength trainer", "HIIT"],
    coordinates: ["-76.99150498902702", "39.26963917243854"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata",
  },
  {
    id: "68",
    name: "Kaila Gaeta",
    image: require("../../assets/dummy/jefferson.png"),
    rating: 4.0,
    age: "32",
    categories: ["Swimming", "Yoga"],
    coordinates: ["-77.19954973839795", "38.86997238274489"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
  },
  {
    id: "69",
    name: "Charla Bradsher",
    image: require("../../assets/dummy/kaitlyn.png"),
    rating: 4.0,
    age: "31",
    categories: ["Tai Chi", "Swimming"],
    coordinates: ["-77.04046487480556", "39.46554387711011"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
  },
  {
    id: "70",
    name: "Leonel Cowman",
    image: require("../../assets/dummy/junior.png"),
    rating: 3.5,
    age: "31",
    categories: ["Martial art", "Swimming"],
    coordinates: ["-77.02036193012333", "39.216826772032626"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos",
  },
  {
    id: "71",
    name: "Paulette Farrell",
    image: require("../../assets/dummy/emilia.png"),
    rating: 3.5,
    age: "35",
    categories: ["Strength trainer", "Marathon trainer", "Zumba", "HIIT"],
    coordinates: ["-77.01558949950886", "38.68358028998574"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores",
  },
  {
    id: "72",
    name: "Annita Laforest",
    image: require("../../assets/dummy/kaitlyn.png"),
    rating: 4.0,
    age: "38",
    categories: ["Martial art", "Fitness trainer"],
    coordinates: ["-77.141336782947", "39.23804431800924"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit",
  },
  {
    id: "73",
    name: "Hanh Halbrook",
    image: require("../../assets/dummy/robert.png"),
    rating: 4.0,
    age: "22",
    categories: ["Tai Chi", "Swimming", "Pilates"],
    coordinates: ["-77.23343552336682", "38.96450804977986"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita",
  },
  {
    id: "74",
    name: "Melania Peak",
    image: require("../../assets/dummy/emilia.png"),
    rating: 5.0,
    age: "29",
    categories: ["Fitness trainer", "Swimming", "HIIT"],
    coordinates: ["-77.1135726117023", "38.495556759612036"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd",
  },
  {
    id: "75",
    name: "Milissa Swihart",
    image: require("../../assets/dummy/junior.png"),
    rating: 3.5,
    age: "24",
    categories: ["Strength trainer"],
    coordinates: ["-77.03569550944509", "39.4007197967086"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,",
  },
  {
    id: "76",
    name: "Annita Laforest",
    image: require("../../assets/dummy/kaitlyn.png"),
    rating: 5.0,
    age: "28",
    categories: ["Aerobics", "HIIT"],
    coordinates: ["-77.11128697759071", "39.41774553330346"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua.",
  },
  {
    id: "77",
    name: "Hanh Halbrook",
    image: require("../../assets/dummy/pedro.png"),
    rating: 4.0,
    age: "27",
    categories: ["Strength trainer", "Tai Chi", "Pilates"],
    coordinates: ["-77.14771810086016", "38.383526342034706"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est",
  },
  {
    id: "78",
    name: "Felice Mclarty",
    image: require("../../assets/dummy/emilia.png"),
    rating: 5.0,
    age: "34",
    categories: ["Boxing", "Fitness trainer"],
    coordinates: ["-77.2105488176858", "39.35081695693349"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At",
  },
  {
    id: "79",
    name: "Fae Marsico",
    image: require("../../assets/dummy/jefferson.png"),
    rating: 3.0,
    age: "28",
    categories: ["Yoga", "Swimming", "Aerobics"],
    coordinates: ["-77.07394587899051", "39.05803552412796"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,",
  },
  {
    id: "80",
    name: "Kalyn Dallman",
    image: require("../../assets/dummy/amanda.png"),
    rating: 3.0,
    age: "33",
    categories: ["Martial art", "Strength trainer", "Pilates"],
    coordinates: ["-77.19162610771646", "38.48806726025621"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
  },
  {
    id: "81",
    name: "Maryam Bergh",
    image: require("../../assets/dummy/jefferson.png"),
    rating: 5.0,
    age: "33",
    categories: ["Yoga", "Zumba", "Personal defense"],
    coordinates: ["-77.07950139907098", "39.372214720974505"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et",
  },
  {
    id: "82",
    name: "Minna Duron",
    image: require("../../assets/dummy/emilia.png"),
    rating: 4.5,
    age: "37",
    categories: ["Fitness trainer", "Yoga", "Pilates"],
    coordinates: ["-77.12405009920326", "38.158317371085175"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus",
  },
  {
    id: "83",
    name: "Fae Marsico",
    image: require("../../assets/dummy/pedro.png"),
    rating: 3.5,
    age: "25",
    categories: ["Martial art", "Strength trainer"],
    coordinates: ["-77.09136648370841", "38.69000710457016"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam",
  },
  {
    id: "84",
    name: "Ross Bradstreet",
    image: require("../../assets/dummy/pedro.png"),
    rating: 5.0,
    age: "34",
    categories: ["Boxing", "Pilates"],
    coordinates: ["-77.06908965881058", "39.3029451308972"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo",
  },
  {
    id: "85",
    name: "Pearle Matthies",
    image: require("../../assets/dummy/junior.png"),
    rating: 5.0,
    age: "28",
    categories: ["Boxing"],
    coordinates: ["-77.114963276531", "38.48344837376006"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita",
  },
  {
    id: "86",
    name: "Maryjane Spiller",
    image: require("../../assets/dummy/junior.png"),
    rating: 4.0,
    age: "30",
    categories: ["HIIT"],
    coordinates: ["-76.95020617198375", "38.63962143168058"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam",
  },
  {
    id: "87",
    name: "Lina Granado",
    image: require("../../assets/dummy/amanda.png"),
    rating: 4.0,
    age: "22",
    categories: ["Strength trainer"],
    coordinates: ["-77.1160420602455", "39.0630606045852"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,",
  },
  {
    id: "88",
    name: "Hae Durgin",
    image: require("../../assets/dummy/junior.png"),
    rating: 3.0,
    age: "22",
    categories: ["Aerobics"],
    coordinates: ["-77.1768035727076", "38.49544991669179"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero",
  },
  {
    id: "89",
    name: "Noel Rockwood",
    image: require("../../assets/dummy/robert.png"),
    rating: 5.0,
    age: "35",
    categories: ["Swimming", "Pilates"],
    coordinates: ["-77.05940029621061", "38.5296624797477"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo",
  },
  {
    id: "90",
    name: "Elvina Bartell",
    image: require("../../assets/dummy/jefferson.png"),
    rating: 4.5,
    age: "34",
    categories: ["Martial art", "Yoga"],
    coordinates: ["-77.00799214344661", "38.349539386657625"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam",
  },
  {
    id: "91",
    name: "Antonetta Opie",
    image: require("../../assets/dummy/kaitlyn.png"),
    rating: 3.0,
    age: "25",
    categories: ["Pilates", "Personal defense"],
    coordinates: ["-77.025765132114", "38.90686535083616"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo",
  },
  {
    id: "92",
    name: "Kaycee Castorena",
    image: require("../../assets/dummy/emilia.png"),
    rating: 5.0,
    age: "24",
    categories: ["Martial art"],
    coordinates: ["-77.23279823373123", "38.697663851605355"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et",
  },
  {
    id: "93",
    name: "Kalyn Dallman",
    image: require("../../assets/dummy/kaitlyn.png"),
    rating: 4.0,
    age: "24",
    categories: ["Yoga", "Zumba"],
    coordinates: ["-77.1552498080454", "38.41465850958487"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,",
  },
  {
    id: "94",
    name: "Milissa Swihart",
    image: require("../../assets/dummy/unknown.png"),
    rating: 5.0,
    age: "31",
    categories: ["Swimming"],
    coordinates: ["-77.01505883306878", "39.14005877037556"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd",
  },
  {
    id: "95",
    name: "Jefferey Maclaren",
    image: require("../../assets/dummy/amanda.png"),
    rating: 3.5,
    age: "27",
    categories: ["Marathon trainer", "HIIT"],
    coordinates: ["-77.08906808014916", "39.25946461603473"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor",
  },
  {
    id: "96",
    name: "Adina Carder",
    image: require("../../assets/dummy/kaitlyn.png"),
    rating: 5.0,
    age: "34",
    categories: ["Marathon trainer", "Pilates", "Aerobics"],
    coordinates: ["-76.94481464663822", "38.66244701250451"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero",
  },
  {
    id: "97",
    name: "Myesha Showman",
    image: require("../../assets/dummy/emilia.png"),
    rating: 5.0,
    age: "32",
    categories: ["Swimming"],
    coordinates: ["-77.13376057127904", "38.68635592416268"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam",
  },
  {
    id: "98",
    name: "Leonida Simien",
    image: require("../../assets/dummy/robert.png"),
    rating: 4.5,
    age: "29",
    categories: ["Tai Chi", "Yoga"],
    coordinates: ["-77.03684369111969", "38.262328379432006"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus",
  },
  {
    id: "99",
    name: "Adina Carder",
    image: require("../../assets/dummy/pedro.png"),
    rating: 4.0,
    age: "38",
    categories: ["Martial art", "Marathon trainer"],
    coordinates: ["-76.9525892435685", "38.724969954724834"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo",
  },
];
