"use strict";

var React = require("react-native");

var { StyleSheet } = React;

module.exports = [
  {
    id: "0",
    name: "Temika Stearns",
    image: require("../../assets/dummy/junior.jpg"),
    rating: 3.5,
    age: "22",
    categories: ["Marathon trainer", "Pilates"],
    coordinates: ["-76.98560533614696", "38.82546297092634"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,",
  },
  {
    id: "1",
    name: "Myesha Showman",
    image: require("../../assets/dummy/emilia.jpg"),
    rating: 4.0,
    age: "22",
    categories: ["Boxing", "Marathon trainer", "HIIT"],
    coordinates: ["-77.05254981348808", "39.57097580531285"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita",
  },
  {
    id: "2",
    name: "Leonel Cowman",
    image: require("../../assets/dummy/kaitlyn.jpg"),
    rating: 5.0,
    age: "34",
    categories: ["Fitness trainer", "HIIT"],
    coordinates: ["-77.0938514088363", "39.098717056863094"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo",
  },
  {
    id: "3",
    name: "Willy Bergdoll",
    image: require("../../assets/dummy/robert.jpg"),
    rating: 4.5,
    age: "36",
    categories: ["Strength trainer", "Yoga", "Pilates", "Personal defense"],
    coordinates: ["-77.17322790811528", "39.22875067064474"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,",
  },
  {
    id: "4",
    name: "Michel Curnutte",
    image: require("../../assets/dummy/unknown.png"),
    rating: 3.5,
    age: "22",
    categories: ["Martial art", "HIIT"],
    coordinates: ["-77.0528794266397", "39.54907610777148"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea",
  },
  {
    id: "5",
    name: "Maryjane Spiller",
    image: require("../../assets/dummy/amanda.jpg"),
    rating: 5.0,
    age: "22",
    categories: ["Zumba"],
    coordinates: ["-77.1174960496061", "38.779892119401694"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et",
  },
  {
    id: "6",
    name: "Felice Mclarty",
    image: require("../../assets/dummy/unknown.png"),
    rating: 5.0,
    age: "21",
    categories: ["Marathon trainer", "Swimming", "Personal defense"],
    coordinates: ["-77.11084795015037", "38.21079235844194"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est",
  },
  {
    id: "7",
    name: "Lavinia Madry",
    image: require("../../assets/dummy/kaitlyn.jpg"),
    rating: 3.0,
    age: "37",
    categories: ["HIIT"],
    coordinates: ["-76.96686144217894", "39.15414816143431"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est",
  },
  {
    id: "8",
    name: "Annita Laforest",
    image: require("../../assets/dummy/amanda.jpg"),
    rating: 3.5,
    age: "31",
    categories: ["Boxing", "Zumba"],
    coordinates: ["-77.1715178883798", "38.62058314304216"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata",
  },
  {
    id: "9",
    name: "Sergio Morvant",
    image: require("../../assets/dummy/junior.jpg"),
    rating: 3.0,
    age: "27",
    categories: ["Martial art", "Strength trainer", "Personal defense"],
    coordinates: ["-77.00548134703541", "39.490086229142804"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,",
  },
  {
    id: "10",
    name: "Rick Schissler",
    image: require("../../assets/dummy/robert.jpg"),
    rating: 5.0,
    age: "20",
    categories: ["Martial art", "Marathon trainer"],
    coordinates: ["-77.15980467485593", "39.329390494101354"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea",
  },
  {
    id: "11",
    name: "Clark Cloe",
    image: require("../../assets/dummy/junior.jpg"),
    rating: 4.0,
    age: "37",
    categories: ["Boxing", "Martial art"],
    coordinates: ["-77.052993509124", "38.20349476062327"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est",
  },
  {
    id: "12",
    name: "Leonila Childs",
    image: require("../../assets/dummy/pedro.jpg"),
    rating: 5.0,
    age: "26",
    categories: ["Boxing", "HIIT", "Personal defense"],
    coordinates: ["-77.17485883671313", "39.476286380563806"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et",
  },
  {
    id: "13",
    name: "Myesha Showman",
    image: require("../../assets/dummy/robert.jpg"),
    rating: 4.5,
    age: "29",
    categories: ["Strength trainer", "Aerobics", "HIIT"],
    coordinates: ["-77.1954015163611", "39.38152655686795"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed",
  },
  {
    id: "14",
    name: "Hertha Nachman",
    image: require("../../assets/dummy/robert.jpg"),
    rating: 3.5,
    age: "26",
    categories: ["Yoga", "Aerobics"],
    coordinates: ["-77.12611855597832", "38.89865032719273"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita",
  },
  {
    id: "15",
    name: "Jefferey Maclaren",
    image: require("../../assets/dummy/pedro.jpg"),
    rating: 4.5,
    age: "26",
    categories: ["Strength trainer", "Pilates"],
    coordinates: ["-77.1978466231042", "38.51315389832563"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea",
  },
  {
    id: "16",
    name: "Gerry Hutchinson",
    image: require("../../assets/dummy/pedro.jpg"),
    rating: 3.5,
    age: "20",
    categories: ["Fitness trainer", "Tai Chi"],
    coordinates: ["-76.96500262161685", "38.580802300930365"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam",
  },
  {
    id: "17",
    name: "Lionel Coburn",
    image: require("../../assets/dummy/robert.jpg"),
    rating: 4.5,
    age: "23",
    categories: ["Fitness trainer", "Marathon trainer"],
    coordinates: ["-77.11421113606276", "38.726245381543976"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
  },
  {
    id: "18",
    name: "Kari Kesler",
    image: require("../../assets/dummy/unknown.png"),
    rating: 5.0,
    age: "21",
    categories: ["Boxing", "Fitness trainer", "Personal defense"],
    coordinates: ["-77.20482696235742", "38.485106416122065"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
  },
  {
    id: "19",
    name: "Mckinley Moisan",
    image: require("../../assets/dummy/robert.jpg"),
    rating: 5.0,
    age: "24",
    categories: ["Tai Chi"],
    coordinates: ["-77.11540577862783", "38.592529710148824"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero",
  },
  {
    id: "20",
    name: "Fae Marsico",
    image: require("../../assets/dummy/junior.jpg"),
    rating: 4.5,
    age: "30",
    categories: ["Martial art"],
    coordinates: ["-77.0253114847983", "38.82227672632195"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo",
  },
  {
    id: "21",
    name: "Elfrieda Diniz",
    image: require("../../assets/dummy/kaitlyn.jpg"),
    rating: 4.0,
    age: "26",
    categories: ["Pilates"],
    coordinates: ["-76.93583321096129", "39.11604311706683"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam",
  },
  {
    id: "22",
    name: "Maryam Bergh",
    image: require("../../assets/dummy/kaitlyn.jpg"),
    rating: 4.0,
    age: "33",
    categories: ["Strength trainer", "Marathon trainer"],
    coordinates: ["-76.93473745584934", "39.39775695890846"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no",
  },
  {
    id: "23",
    name: "Adina Carder",
    image: require("../../assets/dummy/unknown.png"),
    rating: 3.5,
    age: "30",
    categories: ["Tai Chi"],
    coordinates: ["-77.00007501507545", "38.705754419175754"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus",
  },
  {
    id: "24",
    name: "Michel Curnutte",
    image: require("../../assets/dummy/emilia.jpg"),
    rating: 4.0,
    age: "25",
    categories: ["Martial art", "Tai Chi"],
    coordinates: ["-76.9810598369201", "39.174125379776825"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed",
  },
  {
    id: "25",
    name: "Easter Flake",
    image: require("../../assets/dummy/kaitlyn.jpg"),
    rating: 5.0,
    age: "34",
    categories: ["Pilates"],
    coordinates: ["-76.96035300506314", "38.70078811398387"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam",
  },
  {
    id: "26",
    name: "Gwyn Weatherford",
    image: require("../../assets/dummy/amanda.jpg"),
    rating: 4.5,
    age: "32",
    categories: ["Boxing", "Pilates"],
    coordinates: ["-77.01450454051253", "38.17970006062339"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero",
  },
  {
    id: "27",
    name: "Donny Arledge",
    image: require("../../assets/dummy/kaitlyn.jpg"),
    rating: 3.5,
    age: "37",
    categories: ["HIIT"],
    coordinates: ["-77.08444694411405", "38.988958406707106"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus",
  },
  {
    id: "28",
    name: "Rachell Tallarico",
    image: require("../../assets/dummy/pedro.jpg"),
    rating: 5.0,
    age: "26",
    categories: ["Strength trainer", "Martial art", "Swimming", "HIIT"],
    coordinates: ["-77.00387536369566", "39.200898190902436"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo",
  },
  {
    id: "29",
    name: "Elana Coulson",
    image: require("../../assets/dummy/junior.jpg"),
    rating: 3.5,
    age: "20",
    categories: ["Yoga"],
    coordinates: ["-76.96312728390792", "38.899130558989945"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero",
  },
  {
    id: "30",
    name: "Gerda Isherwood",
    image: require("../../assets/dummy/pedro.jpg"),
    rating: 5.0,
    age: "35",
    categories: ["HIIT"],
    coordinates: ["-77.1265054136379", "38.923304964753605"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores",
  },
  {
    id: "31",
    name: "Boyce Neiman",
    image: require("../../assets/dummy/kaitlyn.jpg"),
    rating: 5.0,
    age: "21",
    categories: ["Martial art", "Pilates", "HIIT"],
    coordinates: ["-77.12399788498502", "38.207900911496644"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd",
  },
  {
    id: "32",
    name: "Melvina Lindblom",
    image: require("../../assets/dummy/emilia.jpg"),
    rating: 5.0,
    age: "39",
    categories: ["Martial art", "Tai Chi", "Zumba", "HIIT"],
    coordinates: ["-77.08280335571554", "38.541609943086264"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no",
  },
  {
    id: "33",
    name: "Hanh Halbrook",
    image: require("../../assets/dummy/kaitlyn.jpg"),
    rating: 4.0,
    age: "28",
    categories: ["Boxing"],
    coordinates: ["-77.17233025799126", "38.68335258670835"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et",
  },
  {
    id: "34",
    name: "Kalyn Dallman",
    image: require("../../assets/dummy/pedro.jpg"),
    rating: 5.0,
    age: "25",
    categories: ["Strength trainer", "Marathon trainer"],
    coordinates: ["-77.208668242623", "38.868381298706076"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam",
  },
  {
    id: "35",
    name: "Jefferey Maclaren",
    image: require("../../assets/dummy/pedro.jpg"),
    rating: 4.0,
    age: "37",
    categories: ["Marathon trainer"],
    coordinates: ["-76.99290376429889", "38.56219305493948"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam",
  },
  {
    id: "36",
    name: "Gerda Isherwood",
    image: require("../../assets/dummy/pedro.jpg"),
    rating: 4.5,
    age: "39",
    categories: ["Zumba", "Personal defense"],
    coordinates: ["-77.12180542359259", "38.409322805543404"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet",
  },
  {
    id: "37",
    name: "Erinn Sawyers",
    image: require("../../assets/dummy/unknown.png"),
    rating: 3.5,
    age: "33",
    categories: ["Yoga", "Pilates"],
    coordinates: ["-77.09905956563632", "38.99006766375306"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea",
  },
  {
    id: "38",
    name: "Deangelo Vanwormer",
    image: require("../../assets/dummy/unknown.png"),
    rating: 3.5,
    age: "22",
    categories: ["Martial art", "Marathon trainer"],
    coordinates: ["-77.1387411717613", "39.511698125887044"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,",
  },
  {
    id: "39",
    name: "Rick Schissler",
    image: require("../../assets/dummy/pedro.jpg"),
    rating: 3.0,
    age: "34",
    categories: ["Martial art", "Marathon trainer", "Swimming", "Aerobics"],
    coordinates: ["-77.12780993414863", "39.07550837259529"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet",
  },
  {
    id: "40",
    name: "Lionel Coburn",
    image: require("../../assets/dummy/robert.jpg"),
    rating: 3.0,
    age: "24",
    categories: ["Boxing", "HIIT"],
    coordinates: ["-77.177996255051", "38.578362465624025"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos",
  },
  {
    id: "41",
    name: "Josh Damiani",
    image: require("../../assets/dummy/amanda.jpg"),
    rating: 4.0,
    age: "22",
    categories: ["Strength trainer", "HIIT"],
    coordinates: ["-77.1543499764846", "38.487095926809566"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea",
  },
  {
    id: "42",
    name: "Gertie Levis",
    image: require("../../assets/dummy/unknown.png"),
    rating: 3.0,
    age: "38",
    categories: ["Boxing"],
    coordinates: ["-77.09088830118823", "39.57897038250126"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,",
  },
  {
    id: "43",
    name: "Willy Bergdoll",
    image: require("../../assets/dummy/robert.jpg"),
    rating: 4.5,
    age: "27",
    categories: ["Martial art", "Pilates", "Aerobics"],
    coordinates: ["-76.8937839366491", "38.943504829781176"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no",
  },
  {
    id: "44",
    name: "Annita Laforest",
    image: require("../../assets/dummy/emilia.jpg"),
    rating: 5.0,
    age: "28",
    categories: ["HIIT"],
    coordinates: ["-76.98127450113745", "39.470013363342275"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita",
  },
  {
    id: "45",
    name: "Brinda Clevinger",
    image: require("../../assets/dummy/kaitlyn.jpg"),
    rating: 3.0,
    age: "25",
    categories: ["Fitness trainer", "Aerobics"],
    coordinates: ["-77.00366078630633", "38.436744864721284"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam",
  },
  {
    id: "46",
    name: "Leonila Childs",
    image: require("../../assets/dummy/kaitlyn.jpg"),
    rating: 4.5,
    age: "39",
    categories: ["Marathon trainer", "Pilates"],
    coordinates: ["-77.02467550933763", "38.396520162742924"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea",
  },
  {
    id: "47",
    name: "Fernande Turnbull",
    image: require("../../assets/dummy/pedro.jpg"),
    rating: 3.0,
    age: "36",
    categories: ["Aerobics"],
    coordinates: ["-77.14987801346226", "39.2878144214401"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero",
  },
  {
    id: "48",
    name: "Jean Engstrom",
    image: require("../../assets/dummy/amanda.jpg"),
    rating: 5.0,
    age: "28",
    categories: ["Swimming", "Aerobics"],
    coordinates: ["-77.00852294321582", "38.28903005732611"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam",
  },
  {
    id: "49",
    name: "Eugenia Barge",
    image: require("../../assets/dummy/unknown.png"),
    rating: 3.0,
    age: "36",
    categories: ["Boxing"],
    coordinates: ["-77.0642010831279", "39.675016163165104"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,",
  },
];
