"use strict";

var React = require("react-native");

var { StyleSheet } = React;

module.exports = [
  {
    id: "0",
    name: "Temika Stearns",
    image: require("../../assets/dummy/junior.jpg"),
    rating: 3.5,
    age: "22",
    categories: ["Marathon trainer", "Pilates"],
    coordinates: ["-76.98560533614696", "38.82546297092634"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,",
    price: 10,
  },
  {
    id: "1",
    name: "Myesha Showman",
    image: require("../../assets/dummy/emilia.jpg"),
    rating: 4.0,
    age: "22",
    categories: ["Boxing", "Marathon trainer", "HIIT"],
    coordinates: ["-77.05254981348808", "39.57097580531285"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita",
    price: 12,
  },
  {
    id: "2",
    name: "Leonel Cowman",
    image: require("../../assets/dummy/kaitlyn.jpg"),
    rating: 5.0,
    age: "34",
    categories: ["Fitness trainer", "HIIT"],
    coordinates: ["-77.0938514088363", "39.098717056863094"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo",
    price: 15,
  },
  {
    id: "3",
    name: "Willy Bergdoll",
    image: require("../../assets/dummy/robert.jpg"),
    rating: 4.5,
    age: "36",
    categories: ["Strength trainer", "Yoga", "Pilates", "Personal defense"],
    coordinates: ["-77.17322790811528", "39.22875067064474"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,",
    price: 8,
  },
  {
    id: "4",
    name: "Michel Curnutte",
    image: require("../../assets/dummy/unknown.png"),
    rating: 3.5,
    age: "22",
    categories: ["Martial art", "HIIT"],
    coordinates: ["-77.0528794266397", "39.54907610777148"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea",
    price: 19,
  },
  {
    id: "5",
    name: "Maryjane Spiller",
    image: require("../../assets/dummy/amanda.jpg"),
    rating: 5.0,
    age: "22",
    categories: ["Zumba"],
    coordinates: ["-77.1174960496061", "38.779892119401694"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et",
    price: 6,
  },
  {
    id: "6",
    name: "Felice Mclarty",
    image: require("../../assets/dummy/unknown.png"),
    rating: 5.0,
    age: "21",
    categories: ["Marathon trainer", "Swimming", "Personal defense"],
    coordinates: ["-77.11084795015037", "38.21079235844194"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est",
    price: 15,
  },
  {
    id: "7",
    name: "Lavinia Madry",
    image: require("../../assets/dummy/kaitlyn.jpg"),
    rating: 3.0,
    age: "37",
    categories: ["HIIT"],
    coordinates: ["-76.96686144217894", "39.15414816143431"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est",
    price: 20,
  },
  {
    id: "8",
    name: "Annita Laforest",
    image: require("../../assets/dummy/amanda.jpg"),
    rating: 3.5,
    age: "31",
    categories: ["Boxing", "Zumba"],
    coordinates: ["-77.1715178883798", "38.62058314304216"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata",
    price: 13,
  },
  {
    id: "9",
    name: "Sergio Morvant",
    image: require("../../assets/dummy/junior.jpg"),
    rating: 3.0,
    age: "27",
    categories: ["Martial art", "Strength trainer", "Personal defense"],
    coordinates: ["-77.00548134703541", "39.490086229142804"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat,",
    price: 17,
  },
  {
    id: "10",
    name: "Rick Schissler",
    image: require("../../assets/dummy/robert.jpg"),
    rating: 5.0,
    age: "20",
    categories: ["Martial art", "Marathon trainer"],
    coordinates: ["-77.15980467485593", "39.329390494101354"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea",
    price: 8,
  },
  {
    id: "11",
    name: "Clark Cloe",
    image: require("../../assets/dummy/junior.jpg"),
    rating: 4.0,
    age: "37",
    categories: ["Boxing", "Martial art"],
    coordinates: ["-77.052993509124", "38.20349476062327"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est",
    price: 10,
  },
  {
    id: "12",
    name: "Leonila Childs",
    image: require("../../assets/dummy/pedro.jpg"),
    rating: 5.0,
    age: "26",
    categories: ["Boxing", "HIIT", "Personal defense"],
    coordinates: ["-77.17485883671313", "39.476286380563806"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et",
    price: 15,
  },
  {
    id: "13",
    name: "Myesha Showman",
    image: require("../../assets/dummy/robert.jpg"),
    rating: 4.5,
    age: "29",
    categories: ["Strength trainer", "Aerobics", "HIIT"],
    coordinates: ["-77.1954015163611", "39.38152655686795"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed",
    price: 14,
  },
  {
    id: "14",
    name: "Hertha Nachman",
    image: require("../../assets/dummy/robert.jpg"),
    rating: 3.5,
    age: "26",
    categories: ["Yoga", "Aerobics"],
    coordinates: ["-77.12611855597832", "38.89865032719273"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita",
    price: 10,
  },
  {
    id: "15",
    name: "Jefferey Maclaren",
    image: require("../../assets/dummy/pedro.jpg"),
    rating: 4.5,
    age: "26",
    categories: ["Strength trainer", "Pilates"],
    coordinates: ["-77.1978466231042", "38.51315389832563"],
    description: "Lorem ipsum dolor sit amet, consetetur sadipscing",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea",
    price: 20,
  },
  {
    id: "16",
    name: "Gerry Hutchinson",
    image: require("../../assets/dummy/pedro.jpg"),
    rating: 3.5,
    age: "20",
    categories: ["Fitness trainer", "Tai Chi"],
    coordinates: ["-76.96500262161685", "38.580802300930365"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam",
    price: 16,
  },
  {
    id: "17",
    name: "Lionel Coburn",
    image: require("../../assets/dummy/robert.jpg"),
    rating: 4.5,
    age: "23",
    categories: ["Fitness trainer", "Marathon trainer"],
    coordinates: ["-77.11421113606276", "38.726245381543976"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et",
    price: 18,
  },
  {
    id: "18",
    name: "Kari Kesler",
    image: require("../../assets/dummy/unknown.png"),
    rating: 5.0,
    age: "21",
    categories: ["Boxing", "Fitness trainer", "Personal defense"],
    coordinates: ["-77.20482696235742", "38.485106416122065"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.",
    price: 10,
  },
  {
    id: "19",
    name: "Mckinley Moisan",
    image: require("../../assets/dummy/robert.jpg"),
    rating: 5.0,
    age: "24",
    categories: ["Tai Chi"],
    coordinates: ["-77.11540577862783", "38.592529710148824"],
    description: "Lorem ipsum dolor sit amet,",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero",
    price: 8,
  },
  {
    id: "20",
    name: "Fae Marsico",
    image: require("../../assets/dummy/junior.jpg"),
    rating: 4.5,
    age: "30",
    categories: ["Martial art"],
    coordinates: ["-77.0253114847983", "38.82227672632195"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo",
    price: 12,
  },
  {
    id: "21",
    name: "Elfrieda Diniz",
    image: require("../../assets/dummy/kaitlyn.jpg"),
    rating: 4.0,
    age: "26",
    categories: ["Pilates"],
    coordinates: ["-76.93583321096129", "39.11604311706683"],
    description: "Lorem ipsum dolor sit amet, consetetur",
    biography:
      "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam",
    price: 10,
  },
];
